### ISSUE TITLE
App from this sample building two web services

### ISSUE THREAD

**Issue by computermouth** [digitalocean/sample-dockerfile#20]
Using this sample, both from `Choose Sample App` or from my forked copy produces two apps. One seems to be the dockerized app, and the other seems to be a buildpack build of the go app. This seems erroneous

![2023-03-17--1679068105_1216x797_scrot](https://user-images.githubusercontent.com/7377029/225953906-415fde50-62da-4a11-85b0-03c375867683.png)

**Comment by computermouth** [comment]
Furthermore, if I delete the un-dockerized one from the buildspec, it works as expected, one web service remains:
```
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: orca-app
region: tor
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: computermouth/sample-dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: sample-dockerfile
  routes:
  - path: /
  source_dir: /
```

But then if I create a new repo with the same app.yaml, but with a different name, it again builds two services. Some things I've discovered today:

1. upon creating new services, DO does not respect machine sizing (basic-xxs becomes professional-xs * 2)
2. upon creating new services, Dockerized override of buildpack autodetects don't function properly, and builds both a docker service and a (golang in this case) native app.
3. DO updates to the app.yaml can sometimes work in the web ui App Spec editor, while the exact same contents fail from a github push.
4. Irrelevant to this repo, but the dockerized builds for static assets either don't work or are severly under-documented: https://github.com/digitalocean/sample-monorepo/issues/6
